### ISSUE TITLE
哪个是训练文件

### ISSUE THREAD

**Issue by luodi789567890** [lhjthp/HNCT#5]

**Comment by lhjthp** [comment]
train.py

**Comment by lhjthp** [comment]
main.py

**Comment by luodi789567890** [comment]
大佬，快救救我，3倍数的时候报错，public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([16, 3, 256, 256])) that is different to the input size (torch.Size([16, 3, 255, 255])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 33, in main
    t.train()
  File "/public/home/zq_luodi/perl5/3w/HNCT-main/src/trainer.py", line 55, in train
    loss = self.loss(sr, hr)
  File "/public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/zq_luodi/perl5/3w/HNCT-main/src/loss/__init__.py", line 73, in forward
    loss = l['function'](sr, hr)
  File "/public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 101, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "/public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 3263, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/public/home/zq_luodi/.local/lib/python3.8/site-packages/torch/functional.py", line 74, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (255) must match the size of tensor b (256) at non-singleton dimension 3
