### ISSUE TITLE
有关训练问题

### ISSUE THREAD

**Issue by luodi789567890** [lhjthp/HNCT#6]
首先很感谢作者做出的工作，最近研读了作者的文章，十分感兴趣，想要复现作者的代码，在数据集处理上出现了问题，想请教一下作者，是将DIV2K数据集里面的全部文件都要进行预处理吗，全部转化为二进制，本人是小白一个，对代码知识有很大的欠缺，希望大佬有空的时候能解答我的疑惑，我的扣扣是：2715128882，有关训练问题还有问题想和大佬进行请教，最后再一次感谢作者，希望作者在未来的科研道路上大展宏图，一帆风顺！

**Comment by lhjthp** [comment]
二进制那个是默认处理的，不用去管他，等他自己处理完就会开始训练了

**Comment by luodi789567890** [comment]
可是我把数据集放进去，option.py文件的指定路径，运行main.py会自动生成一个bin文件的数据集，但是里面什么都没有，然后报错

**Comment by lhjthp** [comment]
报错截图看一下

**Comment by luodi789567890** [comment]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 28, in main
    loader = data.Data(args)
  File "/root/autodl-tmp/HNCT/src/data/__init__.py", line 28, in __init__
    self.loader_train = dataloader.DataLoader(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 277, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 97, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by luodi789567890** [comment]
# Data specifications
parser.add_argument('--dir_data', type=str, default='DIV2K',
                    help='daptaset directory')
parser.add_argument('--dir_demo', type=str, default='autodl-tmp/HNCT/experiment/test',

**Comment by Shiqi72** [comment]
你好，请问复现成功了吗
