### ISSUE TITLE
复现错误

### ISSUE THREAD

**Issue by luodi789567890** [lhjthp/HNCT#7]
(LR_conv): Conv2d(50, 50, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (upsampler): Sequential(
      (0): Conv2d(50, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): PixelShuffle(upscale_factor=4)
    )
  )
)
372,848 total parameters.
372,848 training parameters.
[Epoch 0]       Learning rate: 5.00e-4
[1600/16000]    [L1: 0.0862]    27.3+4.9s
[3200/16000]    [L1: 0.0660]    27.4+1.1s
[4800/16000]    [L1: 0.0567]    27.6+2.0s
[6400/16000]    [L1: 0.0513]    27.7+0.9s
[8000/16000]    [L1: 0.0479]    27.7+2.2s
[9600/16000]    [L1: 0.0455]    27.9+0.8s
[11200/16000]   [L1: 0.0437]    27.9+0.3s
[12800/16000]   [L1: 0.0423]    28.0+0.2s
[14400/16000]   [L1: 0.0412]    28.0+1.2s
[16000/16000]   [L1: 0.0402]    28.1+0.7s

Evaluation:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main()
  File "main.py", line 34, in main
    t.test()
  File "/root/autodl-tmp/src/trainer.py", line 132, in test
    PSNR_values.append(eval_acc / len(d))
ZeroDivisionError: division by zero

**Comment by kekiii** [comment]
你好，我遇到了同样的问题，请问解决了吗？

**Comment by Bobodesu** [comment]
我把测试集放在生成的benchmark文件夹里就对了，我其实也没搞明白原理
